#define once
#define CRLF "\r\n"
#define ERR_NOTENOUGHPARAMS(nickname) (": 461 " + nickname + ":Not enough parameters" + CRLF)
#define ERR_ALREADYONCHANNEL(nick, channel) (":localhost 443 " + nick + " #" + channel + " :You're already on that channel" + CRLF)
#define ERR_PASSWDMISMATCH(nickname) (": 464 " + nickname + ":Password incorrect" + CRLF)
#define ERR_ALREADYREGISTRED(nickname) (": 462 " + nickname + ":Unauthorized command (already registered)" + CRLF)
#define ERR_NICKINUSE(nickname) (": 433 " + nickname + " :Nickname is already in use" + CRLF)
#define ERR_ERRONEUSNICK(nickname) (": 432 " + nickname + " :Erroneus nickname" + CRLF)
#define RPL_NICKCHANGE(oldnickname, nickname) (":" + oldnickname + " NICK " + nickname + CRLF)
#define RPL_CONNECTED(nickname) (": 001 " + nickname + " : Welcome to the IRC server!" + CRLF)
#define ERR_NOTREGISTERED(nickname) (": 451 " + nickname + " :You have not registered!" + CRLF)
#define RPL_JOINMSG(hostname, ipaddress, channelname) (":" + hostname + "@" + ipaddress + " JOIN #" + channelname + CRLF)
#define RPL_NOTOPIC(nickname, channelname) (": 331 " + nickname + " #" + channelname + " :No topic is set" + CRLF)
#define RPL_TOPICIS(nickname, channelname, topic) (": 332 " + nickname + " #" + channelname + " :" + topic + CRLF)
#define RPL_TOPICWHOTIME(nickname, channelname, setter, epoch) (": 333 " + nickname + " #" + channelname + " " + setter + " " + epoch + CRLF)
#define RPL_CREATIONTIME(nickname, channelname, creationtime) (": 329 " + nickname + " #" + channelname + " " + creationtime + CRLF)
#define RPL_NAMREPLY(nickname, channelname, clientslist) (": 353 " + nickname + " @ #" + channelname + " :" + clientslist + CRLF)
#define RPL_ENDOFNAMES(nickname, channelname) (": 366 " + nickname + " #" + channelname + " :END of /NAMES list" + CRLF)
#define ERR_NEEDMOREPARAMS(nickname, command) (": 461 " + nickname + " " + command + " :Not enough parameters" + CRLF)
#define ERR_TOOMANYTARGETS(nickname, command) (": 407 " + nickname + " " + command + " :Too many channels" + CRLF)
#define ERR_CHANNELNOTFOUND(nickname, channelnameAsTyped) (": 403 " + nickname + " " + channelnameAsTyped + " :No such channel" + CRLF)
#define ERR_TOOMANYCHANNELS(nickname, channelname) (": 405 " + nickname + " #" + channelname + " :You have joined too many channels" + CRLF)
#define ERR_BADCHANNELKEY(nickname, channelname) (": 475 " + nickname + " #" + channelname + " :Cannot join channel (+k)" + CRLF)
#define ERR_INVITEONLYCHAN(nickname, channelname) (": 473 " + nickname + " #" + channelname + " :Cannot join channel (+i)" + CRLF)
#define ERR_CHANNELISFULL(nickname, channelname) (": 471 " + nickname + " #" + channelname + " :Cannot join channel (+l)" + CRLF)
#define ERR_NOTREGISTERED(nickname) (": 451 " + nickname + " :You have not registered!" + CRLF)
#define RPL_INVITING(inviter, target, channel) (": 341 " + inviter + " " + target + " #" + channel + CRLF)
#define RPL_INVITE(host, ip, target, channel) (":" + host + "@" + ip + " INVITE " + target + " :#" + channel + CRLF)
#define ERR_NOSUCHNICK(nick, target) (": 401 " + nick + " " + target + " :No such nick/channel" + CRLF)
#define ERR_USERONCHANNEL(nick, target, channel) (": 443 " + nick + " " + target + " #" + channel + " :is already on channel" + CRLF)
#define RPL_CHANNELMODES(nick, ch, modes) (": 324 " + nick + " #" + ch + " " + modes + CRLF)
#define ERR_NEEDMODEPARM(ch, mode) (": 696 #" + ch + " * You must specify a parameter for the key mode. " + mode + CRLF)
#define ERR_KEYSET(ch) (": 467 #" + ch + " Channel key already set. " CRLF)
#define ERR_INVALIDMODEPARM(ch, mode) (": 696 #" + ch + " Invalid mode parameter. " + mode + CRLF)
#define ERR_UNKNOWNMODE(nick, ch, mode) (": 472 " + nick + " #" + ch + " " + mode + " :is not a recognised channel mode" + CRLF)
#define ERR_NOTONCHANNEL(nick, ch) (": 442 " + nick + " #" + ch + " :You're not on that channel" + CRLF)
#define ERR_CHANOPRIVSNEEDED(nick, ch) (": 482 " + nick + " #" + ch + " :You're not channel operator" + CRLF)
#define RPL_CHANGEMODE(host, ch, mode, args) (":" + host + " MODE #" + ch + " " + mode + (args.empty() ? "" : (" " + args)) + CRLF)
#define RPL_QUIT(nick, user, host, msg) (":" + nick + "!" + user + "@" + host + " QUIT :" + msg + CRLF)
#define RPL_KICK(kicker, channel, target, comment) (":" + kicker + " KICK #" + channel + " " + target + " :" + comment + CRLF)
#define ERR_USERNOTINCHANNEL(nick, target, channel) (": 441 " + nick + " " + target + " #" + channel + " :They aren't on that channel" + CRLF)
#define ERR_NORECIPIENT(nick, command) (": 411 " + nick + " :No recipient given (" + command + ")" + CRLF)
#define ERR_NOTEXTTOSEND(nick) (": 412 " + nick + " :No text to send" + CRLF)
#define ERR_CANNOTSENDTOCHAN(nick, channelname) (": 404 " + nick + " #" + channelname + " :Cannot send to channel" + CRLF)
